"""empty message

Revision ID: 0aae5e54bc2c
Revises: 376c4b0cc607
Create Date: 2023-10-26 03:57:55.680099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aae5e54bc2c'
down_revision = '376c4b0cc607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=False),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('entry', sa.String(length=10), nullable=True),
    sa.Column('target', sa.String(length=10), nullable=True),
    sa.Column('stop', sa.String(length=10), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    # ### end Alembic commands ###
