"""empty message

Revision ID: 48141d351724
Revises: 89227739e4ac
Create Date: 2023-10-22 03:37:48.196727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48141d351724'
down_revision = '89227739e4ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listingdate', sa.String(length=100), nullable=True))
        batch_op.drop_column('listing_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_date', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('listingdate')

    # ### end Alembic commands ###
