"""empty message

Revision ID: 50a7e66ec1c3
Revises: 43af5077c4ef
Create Date: 2023-10-31 06:45:44.393170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50a7e66ec1c3'
down_revision = '43af5077c4ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strategy', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('entry_price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sell_price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('target_price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stop_price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('created_date', sa.String(length=50), nullable=True))
        batch_op.alter_column('comments',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('stop')
        batch_op.drop_column('entry')
        batch_op.drop_column('target')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('entry', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('stop', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('comments',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('created_date')
        batch_op.drop_column('status')
        batch_op.drop_column('stop_price')
        batch_op.drop_column('target_price')
        batch_op.drop_column('sell_price')
        batch_op.drop_column('entry_price')
        batch_op.drop_column('amount')
        batch_op.drop_column('strategy')

    # ### end Alembic commands ###
