"""empty message

Revision ID: 784a4c9730c8
Revises: 50a7e66ec1c3
Create Date: 2023-11-05 08:34:18.864243

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '784a4c9730c8'
down_revision = '50a7e66ec1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_date', sa.String(length=255), nullable=False))

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('entry_price',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('created_date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.alter_column('created_date',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('entry_price',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('portfolio_transactions', schema=None) as batch_op:
        batch_op.drop_column('entry_date')

    # ### end Alembic commands ###
