"""empty message

Revision ID: 89227739e4ac
Revises: 92c878b96c12
Create Date: 2023-10-22 03:37:13.839184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89227739e4ac'
down_revision = '92c878b96c12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('companyname', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sectorname', sa.String(length=100), nullable=True),
    sa.Column('subsectorname', sa.String(length=100), nullable=True),
    sa.Column('listing_date', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    # ### end Alembic commands ###
